force-app/main/default/objects/Account/fields/Total_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Licenses__c</fullName>
    <label>Total Licenses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Instance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Instances</relationshipLabel>
    <relationshipName>Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Instance__c/fields/Licenses__c.field-meta.xml
<CustomField>
    <fullName>Licenses__c</fullName>
    <label># Licenses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InstanceTriggerHandlerTest.cls
@isTest public class InstanceTriggerHandlerTest {
	@isTest static void test(){
        Account acc = new Account(Name = 'DOCEBO');
        insert acc;
        Id recordType = Schema.SObjectType.Instance__c.getRecordTypeInfosByName().get('Standard Instance').getRecordTypeId();
        Instance__c ins1 = new Instance__c(Name = 'test 1', RecordTypeId = recordType, Account__c = acc.Id, Licenses__c = 3);
        insert ins1;
        acc = [SELECT Id, Total_Licenses__c FROM Account WHERE ID =: acc.Id];
        system.assertEquals(3, acc.Total_Licenses__c);
        Instance__c ins2 = new Instance__c(Name = 'test 2', RecordTypeId = recordType, Account__c = acc.Id, Licenses__c = 5);
        insert ins2;
        acc = [SELECT Id, Total_Licenses__c FROM Account WHERE ID =: acc.Id];
        system.assertEquals(8, acc.Total_Licenses__c);
        ins1.Licenses__c = 6;
        update ins1;
        acc = [SELECT Id, Total_Licenses__c FROM Account WHERE ID =: acc.Id];
        system.assertEquals(11, acc.Total_Licenses__c);
        delete ins2;
        acc = [SELECT Id, Total_Licenses__c FROM Account WHERE ID =: acc.Id];
        system.assertEquals(6, acc.Total_Licenses__c);
    }
}